### ISSUE TITLE
Investigating improvements

### ISSUE THREAD

**Issue by dignifiedquire** [dominictarr/bench-lru#1]
nvm, will update in the next days..

**Comment by dignifiedquire** [comment]
Was just benching it on my machine 🎉 super nice. 
When reading up on LRU caches, I came across ARC, which I was a reminded of a little with your two cache approach. I wonder if you looked at that in your thinking: http://dbs.uni-leipzig.de/file/ARC.pdf

**Comment by dominictarr** [comment]
no i didn't see that, i just had the idea, but it's pretty simple so
wouldn't be suprised if someone else tried something similar
