### ISSUE TITLE
hyperlru package problem affects fresh installs with node 8.x

### ISSUE THREAD

**Issue by avoidwork** [dominictarr/bench-lru#13]
@Kikobeats I noticed this morning that the `should` module isn't installed with your modules even though it's listed as `latest`, it appears to have a conflict with other requirements such that npm can't install it which results in this project being non-functional on a fresh clone/install/execution.

![screen shot 2017-10-10 at 7 09 25 am](https://user-images.githubusercontent.com/369698/31383855-8e0f267a-ad8a-11e7-8dbd-886b9cf63ca7.png)

![screen shot 2017-10-10 at 7 13 00 am](https://user-images.githubusercontent.com/369698/31383859-91691506-ad8a-11e7-8e17-77477656fd2d.png)

I'd wager it's that "5." vs "latest" that's creating the conflict for npm.

**Comment by avoidwork** [comment]
The `package-lock.json` created by npm is available at https://gist.github.com/avoidwork/94ca81710daed11265f080f3af3a83ba

**Comment by avoidwork** [comment]
imo, this is an npm bug, but i'm not sure how to approach it since it spans across multiple modules brought into this project for testing :/

**Comment by Kikobeats** [comment]
Actually `should` dependency inside `hyperlru` package is not necessary; I release a new patch version removing it, but I suppose this bug need to be reported at npm repository 👍

**Comment by avoidwork** [comment]
cool, i shall report it

**Comment by dominictarr** [comment]
yuk, you should not use `*` module ranges, that is asking for trouble. Anyway, I think these shouldn't be installed anyway because they are dev deps, unless you clone those repos and then install directly.

**Comment by avoidwork** [comment]
Created https://github.com/npm/npm/issues/18784
