### ISSUE TITLE
Please re-test tiny-lru

### ISSUE THREAD

**Issue by avoidwork** [dominictarr/bench-lru#4]
Hi,

I noticed this benchmark & fixed tiny-lru as a result. Thanks for making it! Please re-test the module, it's roughly 150x faster for eviction* on my 2014 macbook air, and 30x faster on my i5-6500 desktop.

This is a screenshot of the HEAD of this repo with only tiny-lru running:

![screen shot 2017-01-05 at 9 14 39 pm](https://cloud.githubusercontent.com/assets/369698/21705204/754a3072-d38c-11e6-850c-32163edd520b.png)

**Comment by dominictarr** [comment]
Great! what change did you make?

my computer broke (am on phone rn) so will add you as collab so you can merge and update!

**Comment by avoidwork** [comment]
Hi,

First change was to minimize new `object` creation which is why there was an overall increase in ops/s. I then did a little trial/error sans irhydra2 (was having trouble with node 7) to determine the `evict` code path from `set` was doing a few too many ops on a single property which was most likely causing the JIT to deop & drop to a "slow zone" / interpreted execution.

I ended up erasing a couple of lines of code, and rearranging some ops to do less work overall 👍
