### ISSUE TITLE
Benchmark reliability

### ISSUE THREAD

**Issue by SkeLLLa** [dominictarr/bench-lru#8]
Hello. I've checked your benchmark and find some interesting results:

```
node --expose-gc index.js
name, set, get1, update, get2, evict
lru-native, 1000, 1563, 1493, 1639, 926
hashlru, 3125, 8333, 5263, 654, 4545
node --expose-gc index.js
name, set, get1, update, get2, evict
hashlru, 9091, 20000, 10000, 7692, 4762
lru-native, 1031, 1563, 1429, 1587, 862
```

Basically when you just swap order of some LRU implementations it could significantly affect others performance.

Probably it will be better and look more trustworthy if all LRU implementations at least will run in separate isolated threads (multiple nodes) or at least in v8 sandbox.

System: node v7.5.0, Linux 4.9.0-pf5 SMP x86_64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz GenuineIntel GNU/Linux

**Comment by dominictarr** [comment]
interesting, although it's worth noting that the _important_ measurement (evict) doesn't change much.
but anyway, I would certainly merge a PR that fixed this!

**Comment by dominictarr** [comment]
there are also other problems, such as it doesn't record any statistical significance, so you can rerun the benchmark again and again until you see the result you want. (and it may be very tempting to do so)

**Comment by dominictarr** [comment]
hmm, hashlru seems particularily effected by this

``` js
[dominic@localhost bench-lru]$ node index.js 
name, set, get1, update, get2, evict
hashlru, 4348, 5556, 6667, 6667, 4545
tiny-lru, 1429, 2381, 2857, 2381, 1149
array-lru, 1370, 1923, 2041, 4348, 1136
[dominic@localhost bench-lru]$ node index.js 
name, set, get1, update, get2, evict
tiny-lru, 1563, 2564, 3333, 2632, 1563
hashlru, 3571, 2857, 4545, 5882, 1563
array-lru, 3571, 3704, 1538, 3571, 2381
```
though, maybe the benchmark would be more realistic if the vm has already got busy before the benchmark runs.

**Comment by SkeLLLa** [comment]
@dominictarr it seems to me that native modules like lru-native can affect other's performance

**Comment by avoidwork** [comment]
@SkeLLLa  when you run them sequentially GC & the JIT state will impact what follows next. I like the idea of splitting them up into child_process to return stdout; might work on that if I have some time.

**Comment by SkeLLLa** [comment]
@avoidwork In my case I've slightly modified bench code by adding global.gc() just before each LRU benchmark and ran node with --expose-gc. So theoretically node shouldn't run main gc during each test phase.

**Comment by avoidwork** [comment]
@SkeLLLa right, I just meant in general (for people reading the thread); does global.gc() clear the inline caches to? I haven't looked it too closely.

**Comment by avoidwork** [comment]
@SkeLLLa I just tried running it with `--expose-gc --trace-gc --log-gc` and some of the slower modules have significant mark & sweeps vs the faster ones having 1 or a few; I think that would be an interesting metric to track as well. thoughts?

**Comment by SkeLLLa** [comment]
@avoidwork inline caching is related to optimization phase and usually in v8 it will happen just after code first execution [details](https://github.com/v8/v8/wiki/Design%20Elements#dynamic-machine-code-generation). So if I'm not mistaken it will be performed on so called "compilation" phase.
Garbage collection is performed in runtime phase, and it only operates with memory searching objects without references. So it should not affect inline caching directly. Probably later v8 deletes unused items from cache, but I've never seen any information about that.

**Comment by avoidwork** [comment]
👍 thanks for clarifying

**Comment by SkeLLLa** [comment]
BTW, you can also pass `--gc_interval` parameter set to some big number to ensure that gc doesn't do some time lag.

I have some ideas about lru benchmarking in conditions that will be closer to real-life, including measuring amount of memory consumed per same object (it is also quiet interesting for me, especially in case of native vs pure-js modules). So when I have some time I'll make PR or probably implement them in separate repo if there will be significant changes.

**Comment by avoidwork** [comment]
single pass stats from an macbook air'14 ... it's interesting. collecting more passes & on different hardware should present relevant data.

```
hashlru			scavenge 5	mark/sweep 0
modern-lru		scavenge 7	mark/sweep 1
lru-cache		scavenge 26	mark/sweep 0
lru_cache		scavenge 2	mark/sweep 0
tiny-lru		scavenge 1	mark/sweep 0
lru			scavenge 1	mark/sweep 1
simple-lru-cache	scavenge 0	mark/sweep 1
mkc			scavenge 19	mark/sweep 1
lru-fast		scavenge 1	mark/sweep 1
faster-lru-cache	scavenge 8	mark/sweep 0
secondary-lru-cache	scavenge 35	mark/sweep 0
```

**Comment by SkeLLLa** [comment]
@avoidwork as for scavenge it will be also interesting to observe how much memory will be freed from heap's `new_space` and how many objects will survive and go to `old_space`. Usually scavenge takes less than 1ms. But in some cases if a lot of objects survive and go from `new_space` to `old_space` it could take longer, so it is possible that 20 scavenges could take less time than 10.

**Comment by dominictarr** [comment]
@avoidwork @SkeLLLa wow, I didn't know you could do that! being able to graph how a given implementation uses memory would be awesome. the whole point of an LRU cache is to make a tradeoff about speed and memory, gc is obviously part of that.

**Comment by dominictarr** [comment]
is it possible to measure the time that v8 spent in GC?

**Comment by dominictarr** [comment]
@avoidwork can you link me to something that explains what scavenging is, in GC?
Also I found this: http://jayconrod.com/posts/55/a-tour-of-v8-garbage-collection which was quite informative

**Comment by SkeLLLa** [comment]
@dominictarr yes, the time spent in gc could be measured in different ways. If you want to trigger it manually run node with `--expose-gc --gc_interval=9999999` and in your code:
```
var time = process.hrtime();
global.gc();
var diff = process.hrtime(time);
console.log(`GC took ${diff[0] * 1e9 + diff[1]} nanoseconds`);
```
or
```
var time = process.hrtime();
global.gc();
setImmidiate(() => {
  var diff = process.hrtime(time);
  console.log(`GC took ${diff[0] * 1e9 + diff[1]} nanoseconds`);
});
```
I don't remember if gc() function is blocking, but I'm pretty sure that it will block event loop.

Also there is a [module](https://www.npmjs.com/package/gc-stats) that also allow to track GC including timing and amount of freed memory. But in case that usally main GC in node happens once per couple of minutes you probably should trigger it manually with `global.gc()` also.

**Comment by dominictarr** [comment]
thanks!

**Comment by Kikobeats** [comment]
Thanks for this @SkeLLLa!

Can you check the current bench implementation?
https://github.com/dominictarr/bench-lru/blob/master/bench.js

Do you think we ca do something for improve the reliability of the suite?

**Comment by SkeLLLa** [comment]
I think that it became much better. Not ideal, because it seems that in different runs it can produce values that differ by 10% or even more. In order to make it much better it should run several times and then apply some math statistics methods to calculate all that stats stuff (like it's done in nodejs repo, for example).

But nevertheless it gives good starting point for making a right choice and it will be obviously useful. Good work.
 
BTW I think it's worth to add something like
```
start: node --predictable index.js
```
to package.json scripts.

**Comment by Kikobeats** [comment]
I'm agree, need to run more than one time and return average stats.

something like https://github.com/mcollina/fastbench

@SkeLLLa can you make a PR about the script? not sure If I understood you.

**Comment by SkeLLLa** [comment]
Yep: https://github.com/dominictarr/bench-lru/pull/11
